# Generated by Django 3.2.5 on 2021-07-08 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_user', '0005_alter_custom_user_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
    ]
