# Generated by Django 3.2.5 on 2021-07-07 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='cans',
            field=models.CharField(max_length=20),
        ),
    ]
